# Generated by Django 5.0.4 on 2024-04-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemedia',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='like',
            name='anime_media',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='anime_media',
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('genre', models.ManyToManyField(to='app.genre')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.director'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(blank=True, upload_to='')),
                ('add_at', models.DateField(auto_now=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.director')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.media'),
        ),
        migrations.AddField(
            model_name='rating',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.media'),
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='AnimeMedia',
        ),
    ]
