# Generated by Django 5.0.4 on 2024-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_animemedia_anime_remove_comment_anime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='title',
            new_name='name',
        ),
    ]
